input_feature: 
input_feature_name: 
batch_size: 
learning_rate: 
early_stopping_patience: 
early_stopping_delay_epochs: 
epochs: 
initial_epoch:
num_batches_train: 
num_batches_val: 
backend:
precomputed_embeddings:
freeze_encoder: 
freeze_epochs:
finetune_learning_rate:
finetune_warmup_epochs:
finetune_decay_epochs: