
input_feature_name: ${embeddings.name}_spatial_embeddings
# labels: 
#   - polyphony_degree
#   - framewise_polyphony
#   - perch2_event_logits
batch_size: 128
learning_rate: 0.0001
epochs: 10
tensorboard_path: debug_tensorboard

use_event_logits: True
num_event_logits: 16
event_logits_name: event_logits

use_framewise_polyphony: True
num_frames: 16
framewise_polyphony_name: framewise_polyphony