# Copyright 2024 tu-studio
# This file is licensed under the Apache License, Version 2.0.
# See the LICENSE file in the root of this project for details.

# Use an official Debian runtime with fixed version as a parent image
FROM debian:13-slim

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    # Python 3.12 and tools
    python3.12 \
    python3.12-venv \
    python3-pip \
    # Build tools 
    build-essential \
    # SSL and compression libraries
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    # Python build dependencies
    libncurses5-dev \
    libgdbm-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    # Audio processing
    libsndfile1 \
    libsndfile1-dev \
    ffmpeg \
    # Utilities
    wget \
    curl \
    git \
    openssh-client \
    rsync \
    # Remove apt cache to reduce image size
    && rm -rf /var/lib/apt/lists/*

# Copy the global.env file
COPY global.env /tmp/global.env

# # Install Python Version
# RUN . /tmp/global.env \
#     && echo "Using Python version: ${TUSTU_PYTHON_VERSION}" \
#     && echo "Downloading Python version: ${TUSTU_PYTHON_VERSION}" \
#     && wget --no-check-certificate https://www.python.org/ftp/python/${TUSTU_PYTHON_VERSION}/Python-${TUSTU_PYTHON_VERSION}.tgz \
#     && tar -xf Python-${TUSTU_PYTHON_VERSION}.tgz \
#     && cd Python-${TUSTU_PYTHON_VERSION} \
#     && ./configure --enable-optimizations \
#     && make -j$(nproc) \
#     && make altinstall \
#     && cd .. \
#     # Delete the unzipped directory and downloaded archive to save space
#     && rm -rf Python-${TUSTU_PYTHON_VERSION} Python-${TUSTU_PYTHON_VERSION}.tgz \
#     # Create symlink for python3
#     && ln -s /usr/local/bin/python${TUSTU_PYTHON_VERSION%.*} /usr/local/bin/python3 \
#     && ln -s /usr/local/bin/python${TUSTU_PYTHON_VERSION%.*} /usr/local/bin/python

# Set the working directory
WORKDIR /home/app

################
# Envs
################

# Base venv (in PATH for DVC and general commands)
RUN python3.12 -m venv /envs/base-venv
ENV PATH="/envs/base-venv/bin:$PATH"
RUN pip install --upgrade pip \
    && pip install dvc dvc-gdrive omegaconf

# Perch venv (call explicitly in DVC stages)
RUN python3.12 -m venv /envs/perch-venv \
    && /envs/perch-venv/bin/pip install --upgrade pip \
    && /envs/perch-venv/bin/pip install \
        git+https://github.com/google-research/perch-hoplite.git \
        tensorflow \
        omegaconf \
        datasets==3.6.0

# BIRDSET ENV
# # Create virtual environment
# RUN python3 -m venv /opt/birdset-env
# ENV PATH="/opt/birdset-env/bin:$PATH"

# # Install your requirements first
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# # Verify ruamel.yaml is installed
# RUN python -c "import ruamel.yaml; print('ruamel.yaml installed successfully')"

# # Then install BirdSet
# RUN git clone --no-recurse-submodules https://github.com/DBD-research-group/BirdSet.git /tmp/birdset && \
#     pip install -e /tmp/birdset && \
#     rm -rf /tmp/birdset

# Final verification
RUN python -c "import ruamel.yaml; import datasets; print('All packages working')"

RUN rm requirements.txt

ENV PYTHONPATH="/home/app/source"



