# This file defines the dvc stages and its depencies

stages:

  # train:
  #   cmd: ${python.complete} source/train.py 
  #   deps:
  #     - source/train.py
  #     - source/utils/logs.py
  #     - source/utils/general.py
  #     - source/utils/config.py
  #     - source/utils/dataset.py
  #     - source/utils/losses.py
  #   params:
  #     - general.random_seed
  #     - dataset
  #     - model
  #     - objectives
  #     - train
  #     - log
  #   outs:
  #     - ${path.train_output}

  train:
    cmd: ${python.complete} source/torch_train.py
    deps:
      - source/train.py
      - source/utils/general.py
      - source/utils/logs.py
      - source/utils/config.py
      - source/utils/dataset.py
      - source/utils/metrics.py
      - source/utils/torch_losses.py
      - source/utils/torch_models.py
      - source/utils/torch_logging.py
    params:
      - general.random_seed
      - dataset
      - model
      - head
      - objectives
      - train
      - log
    outs:
      - ${path.train_output}

  evaluate:
    cmd: ${python.complete} source/evaluate_on_test_split.py
    deps: 
      - source/evaluate_on_test_split.py
      - source/utils/logs.py
      - source/utils/dataset.py
      - source/utils/metrics.py
      - source/utils/evaluation.py
      - source/utils/torch_evaluation.py
      # - ${path.train_output}
      # - source/integrations/birdset.py
      # - source/integrations/perch.py
    params:
      - general.random_seed
      - dataset
      - embeddings
      - model
      - objectives
      - train
      - evaluation
    outs:
      - ${path.eval_output}

  soundscape_evaluate:
    cmd: ${python.complete} source/evaluate_on_soundscape_data.py
    deps: 
      - source/evaluate_on_soundscape_data.py
      - source/utils/logs.py
      - source/utils/dataset.py
      - source/utils/torch_evaluation.py
      - source/utils/metrics.py
      - source/utils/evaluation.py
      # - ${path.train_output}
    params:
      - general.random_seed
      - dataset
      - model
      - objectives
      - train
      - evaluation
    outs:
      - ${path.soundscape_eval_output}

  val_evaluate:
    cmd: ${python.complete} source/evaluate_on_val_split.py
    deps: 
      - source/evaluate_on_val_split.py
      - source/utils/logs.py
      - source/utils/dataset.py
      - source/utils/metrics.py
      - source/utils/evaluation.py
      - source/utils/torch_evaluation.py
      # - ${path.train_output}
      # - source/integrations/birdset.oy
      # - source/integrations/perch.py
    params:
      - general.random_seed
      - dataset
      - embeddings
      - model
      - objectives
      - train
      - evaluation
    outs:
      - ${path.val_eval_output}