# This file defines the dvc stages and its depencies

stages:
  # load_dataset:
  #   cmd:
  #     python source/load_dataset.py
  #   deps:
  #     - source/load_data.py
  #   params:
  #     - dataset.name
  #     - dataset.sampling_rate
  #   outs:
  #     - path.dataset_metadata

  embed_with_perch:
    cmd: envs/perch-venv/bin/python source/embed_audio.py # --version perch_v1 #--model_keys ${train.embeddings}  ${embeddings.perch_v1_models} --compute_embeddings ${embeddings.compute_embeddings}
    params:
      - embeddings
    deps:
      - source/embed_audio.py
      - ${path.dataset_metadata}

  # embed_with_perch2:
  #   cmd: envs/perch-venv/bin/python source/embed_audio.py  --version perch_v2 #--model_keys ${train.embeddings}  ${embeddings.perch_v2_models} --compute_embeddings ${embeddings.compute_embeddings}
  #   params:
  #     - embeddings
  #   deps:
  #     - source/embed_audio.py
  #     - ${path.dataset_metadata}

  # embed_with_birdset:
  #   cmd: python source/embed_audio.py #--version birdset #${embeddings.birdset_models} --compute_embeddings ${embeddings.compute_embeddings}
  #   params:
  #     - embeddings
  #   deps:
  #     - source/embed_audio.py
  #     - ${path.dataset_metadata}

  # add_labels:
  #   cmd: python source/add_labels.py
  #   deps:
  #     - source/add_labels.py

  # train:
  #   cmd: python source/train.py
  #   deps:
  #     - source/train.py
  #     - path.dataset_metadata
  #   params:
  #     - general.random_seed
  #     - train
  #     - model
      

