general:
  random_seed: 42
dataset:
  huggingface_path: mcht67/PolyphonicBirdSet
  subset: HSN
  split: train
embeddings: {}
model:
  _target_: model.SimpleMLP
  hidden_units:
  - 512
  - 256
  dropout_rate: 0.3
objectives:
  polyphony_degree_class:
    loss:
      _target_: tensorflow.keras.losses.SparseCategoricalCrossentropy
      from_logits: true
    weight: 1.0
    confusion_matrix:
      type: classification
    label: polyphony_degree
train:
  input_feature_name: Bird-MAE-Huge_audio_pooled_embeddings
  batch_size: 128
  learning_rate: 0.001
  epochs: 20
  initial_epoch: null
  train_size_batches: null
  val_size_batches: null
log:
  experiment_name: Embeddings-Comparison
  tensorboard_subfolder: Embeddings-Comparison
  tensorboard_suffix: ''
  hyperparameters:
  - train.input_feature_name
path:
  dataset: dataset
  dataset_metadata: stage_results/dataset_metadata.json
  perch_embeddings_metadata: stage_results/perch_embeddings_metadata.json
  birdset_embeddings_metadata: stage_results/birdset_embeddings_metadata.json
  added_labels_metadata: stage_results/added_labels_metadata.json
