general:
  random_seed: 42
dataset:
  huggingface_path: mcht67/Polyphonic-BirdSet-train
  subset: HSN/HSN_polyphonic_8
  max_polyphony: 8
  train_config: HSN_polyphonic_8
  soundscape_config: HSN/HSN_polyphonic_8_soundscape_test
embeddings:
  name: AudioProtoPNet-20-BirdSet-XCL
  type: birdset
  dimension_type: spatial
  model_cfg:
    _target_: torch_models.BirdSetAudioProtoPNet
    pretrained_model_path: DBD-research-group/AudioProtoPNet-20-BirdSet-XCL
    pooling: mean
model:
  _target_: model.TemporalCNN
objectives:
  polyphony_degree:
    loss:
      _target_: tensorflow.keras.losses.MeanSquaredError
    weight: 1.0
    confusion_matrix:
      type: regression_round
      threshold: 0.5
    label: polyphony_degree
  polyphony_degree_class:
    loss:
      _target_: tensorflow.keras.losses.SparseCategoricalCrossentropy
      from_logits: true
    weight: 1.0
    confusion_matrix:
      type: classification
    label: polyphony_degree_class
    num_classes: 9
train:
  input_feature: audio
  input_feature_name: AudioProtoPNet-20-BirdSet-XCL_audio_spatial_embeddings
  batch_size: 32
  learning_rate: 0.001
  early_stopping_patience: 20
  epochs: 100
  initial_epoch: null
  num_batches_train: null
  num_batches_val: null
log:
  study_name: Spatial-Embeddings
  exp_name: test-exp
  keep_last_n_checkpoints: 5
  hyperparameters:
  - model
  - train.input_feature
  - embeddings
  - objectives
  - dataset.subset
  - dataset.train_config
  metrics:
  - val_loss
  - val_accuracy
  - val_polyphony_degree_loss
  - val_polyphony_degree_class_loss
  - val_event_logits_loss
  - val_framewise_polyphony_loss
  - val_framewise_polyphony_class_loss
  - val_polyphony_degree_accuracy
  - val_polyphony_degree_class_accuracy
  - val_event_logits_accuracy
  - val_framewise_polyphony_accuracy
  - val_framewise_polyphony_class_accuracy
datetime: '20260603_011307'
path:
  study_subfolder: AudioProtoPNet-20-BirdSet-XCL/
  train_output: train_output/Spatial-Embeddings/AudioProtoPNet-20-BirdSet-XCL/
  eval_output: eval_output/Spatial-Embeddings/AudioProtoPNet-20-BirdSet-XCL/
python:
  base: venv/bin/python
  perch: perch-venv/bin/python
  train: train-venv/bin/python
  complete: /opt/complete-venv/bin/python
