general:
  random_seed: 42
dataset:
  name: DBD-research-group/BirdSet
  subset: HSN_xc
  split: train
  sampling_rate: 32000
  segment_duration: 5
  max_polyphony_degree: 7
embeddings:
  models:
  - perch_8
  - yamnet
  feature: audio
preprocess:
  input_path: data/raw/
  output_file_path: data/processed/data.pt
  test_split: 0.2
model:
  _target_: model.SimpleMLP
  hidden_units:
  - 512
  - 256
  dropout_rate: 0.3
train:
  features: perch_8_embeddings
  labels: polyphony_degree
  test_split: 0.1
  val_split: 0.1
  batch_size: 128
  learning_rate: 0.05
  epochs: 50
export:
  output_file_path: models/exports/model.pth
paths:
  raw_dataset: data/raw_datasets/HSN_xc
  polyphonic_dataset: data/polyphonic_datasets/HSN_xc_polyphonic
  preprocessed_dataset: data/preprocessed_datasets/HSN_xc_preprocessed
