species_polyphony_class:
  loss:
    _target_: tensorflow.keras.losses.SparseCategoricalCrossentropy
    from_logits: true
  weight: 1.0
  confusion_matrix:
    type: species_classification
  num_classes: 