# ==============================================
# CHANGING THESE COULD BREAK DVC TRACKING
path:
  dataset: data/${dataset.config}/
  dataset_metadata: stage_results/dataset_metadata.json
  perch_embeddings_metadata: stage_results/perch_embeddings_metadata.json
  birdset_embeddings_metadata: stage_results/birdset_embeddings_metadata.json
  added_labels_metadata: stage_results/added_labels_metadata.json
  # epoch_weights_path: checkpoints/epoch_weights/
  # best_weights_path: checkpoints/best_weights/
  # resumable_checkpoint_path: checkpoints/resumable_checkpoint/
# ==============================================


# ==============================================  
python:
  base: venv/bin/python # Default for local runs without docker, overridden by exp_workflow.sh
  perch: perch-venv/bin/python # Default for local runs without docker, overridden by exp_workflow.sh
  train: train-venv/bin/python # Default for local runs without docker, overridden by exp_workflow.sh
# ============================================== 


hydra:
  run:
    dir: .
  job:
    # Deactivates the change of the working directory
    chdir: false
  # Deactivates the hydra logging
  output_subdir: null
  job_logging:
    disable_existing_loggers: false

defaults:
  # It is possible to combine multiple configurations for the same model by using a list e.g. ["v1", "causal"]
  - general: default
  - dataset: default #empty # should be defined in multi_submission
  #- labels: all
  - embeddings: default # # should be defined in multi_submission
  #- preprocess: default
  - model: default #empty
  - objectives: default #empty # should be defined in multi_submission
  - train: 'default'
  - log: 'default'
  - _self_

  