# ==============================================
# CHANGING THESE COULD BREAK DVC TRACKING
path:
  dataset: dataset
  dataset_metadata: stage_results/dataset_metadata.json
# ==============================================

hydra:
  run:
    dir: .
  job:
    # Deactivates the change of the working directory
    chdir: false
  # Deactivates the hydra logging
  output_subdir: null
  job_logging:
    disable_existing_loggers: false

defaults:
  # It is possible to combine multiple configurations for the same model by using a list e.g. ["v1", "causal"]
  - general: default
  - dataset: default
  - embeddings: default
  #- preprocess: default
  - model: 'TemporalCNN'
  - train: 'default'
  - _self_

  