name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
      - 'complete_requirements.txt'
      - '.github/workflows/docker_image.yml'
      - 'global.env'
    # tags:
    #   - 'v*.*.*'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'complete_requirements.txt'
      - '.github/workflows/docker_image.yml'
      - 'global.env'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Free disk space (aggressive)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    # - name: Free disk space
    #   run: |
    #     sudo docker image prune --all --force
    #     sudo rm -rf /usr/share/dotnet
    #     sudo rm -rf /usr/local/lib/android
    #     sudo rm -rf /opt/ghc
    #     sudo rm -rf /opt/hostedtoolcache/CodeQL
    #     df -h  # print available space so you can see the result in logs

    - name: Load Environment Variables from global.env
      run: |
        grep -v '^#' global.env | grep '=' | while IFS='=' read -r key value; do
          if [[ -n "$key" && -n "$value" ]]; then
            echo "$key=$value" >> $GITHUB_ENV
          fi
        done

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64 #,linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-image:latest
        build-args: |
          DOCKER_COMPLETE_VENV=${{ env.DOCKER_COMPLETE_VENV }}